# Generated by Django 4.1 on 2022-08-29 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psg_cse_api', '0002_alter_calc_declared_value_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calc',
            name='declared_value_rate',
            field=models.IntegerField(default=1, verbose_name='Объявленная стоимость груза'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calc',
            name='delivery_type',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='psg_cse_api.deliverytype', verbose_name='Тип доставки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calc',
            name='insurance_rate',
            field=models.IntegerField(default=1, verbose_name='Страховая стоимость груза'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calc',
            name='urgency',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='psg_cse_api.urgency', verbose_name='Срочность доставки'),
            preserve_default=False,
        ),
    ]
